### PR TITLE
Add phpunit-json-assert and phpunit-psr7-assert to extension list

### LINKED ISSUE #27: Adding two more libraries to "Extensions" page?
Hello Sebastian,

I just noticed the "extensions" page on the PHPUnit website and was wondering if you'd be willing to accept pull requests to add a few more to that list. I'm asking since I've been sitting on a few PHPUnit extension libraries that I've been maintaining for a while now and I think might fit well into that list (more precisely, my [phpunit-json-assert](https://github.com/martin-helmich/phpunit-json-assert) and [phpunit-psr7-assert](https://github.com/martin-helmich/phpunit-psr7-assert) package).

Thoughts?

### PR DESCRIPTION
**Pull request by martin-helmich**
Fixes #27

### CODE REVIEW

**Comment by keradus** [comment]
I'm wondering, in general...
maybe there shall be some indicator what to add and what to not, like, adding only maintainable and established positions?
- number of regular maintainers > 1
- some stars / downloads

**Comment by jrfnl** [comment]
@keradus Sorry to be a cynic, but that first criteria would disqualify PHPUnit itself....

**Comment by martin-helmich** [comment]
@sebastianbergmann I noticed that this has been open for a while now (almost a year to the day). Any new thoughts on this?

**Comment by sebastianbergmann** [comment]
TBH, I would much rather remove the `https://phpunit.de/extensions.html` page than add new extensions to it.

**Comment by sebastianbergmann** [comment]
I decided to remove the extensions page. I do not think (anymore) that such a list should be hosted on PHPUnit's website or that I should be the one curating it.

**Pull request closed without merging**
