### PR TITLE
Upgrade to bootstrap 4

### PR DESCRIPTION
**Pull request by rpkamp**
Improving responsiveness of the website for mobile devices on the way

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Thanks!

Do you also want to update the HTML code coverage report to Bootstrap 4? :-)

**Comment by rpkamp** [comment]
Yes that sounds good. I'll look into it.

Also, would you be interested in a very basic templating system for this website? Doesn't have to be anything fancy, just a simple front controller index.php that uses Twig to render the requested URL. No database, no framework, just a simple Twig solution. 

It would certainly make the site more maintainable and easier to upgrade in the future :smile:

**Comment by sebastianbergmann** [comment]
No, I am not interested in using a template system for this website.

**Comment by rpkamp** [comment]
OK cool. Glad I asked before I implemented it :-)

**Pull request merged**
